version: '3.8'

services:
  mcp-gateway:
    build:
      context: .
      dockerfile: docker/Dockerfile.gateway
    ports:
      - "9000:9000"
    networks:
      - caepa-network
    depends_on:
      - backend
      - gdpr-service
      - hipaa-service

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - CEREBRAS_API_KEY=${CEREBRAS_API_KEY}
    networks:
      - caepa-network

  gdpr-service:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8001:8000"
    environment:
      - CEREBRAS_API_KEY=${CEREBRAS_API_KEY}
      - COMPLIANCE_DOMAIN=GDPR
    networks:
      - caepa-network

  hipaa-service:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8002:8000"
    environment:
      - CEREBRAS_API_KEY=${CEREBRAS_API_KEY}
      - COMPLIANCE_DOMAIN=HIPAA
    networks:
      - caepa-network

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "8501:8501"
    depends_on:
      - mcp-gateway
    networks:
      - caepa-network

networks:
  caepa-network:
    driver: bridge